name: Update PB

on:
  push:
    paths:
      - '_pages/docs/PB/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate RB Markdown Links 
      run: |
        chmod a+x ./bash_scripts/update_pb.sh
        ./bash_scripts/update_pb.sh
        
