name: Update Candidatura

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up VM
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Clear file
    - run: echo -n "" > prova.md

    - name: Generate Markdown Links
      run: |
        chmod +x ./bash_scripts/process_subfolders_candidatura.sh
        ./bash_scripts/process_subfolders_candidatura.sh
        
