name: Update RTB

on:
  push:
    paths:
      - '_pages/docs/RTB/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate RTB Markdown Links 
      run: |
        chmod a+x ./bash_scripts/update_rtb.sh
        ./bash_scripts/update_rtb.sh
        
