name: Update PB

on:
  push:
    branches:
      - site-docs
    paths:
      - '3 - PB/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate Candidatura Markdown Links 
      run: |
        chmod a+x ./bash_scripts/update_pb.sh
        ./bash_scripts/update_pb.sh
