name: Update RTB

on:
  push:
    branches:
      - site-docs
    paths:
      - '2 - RTB/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate Candidatura Markdown Links 
      run: |
        chmod a+x ./bash_scripts/update_rtb.sh
        ./bash_scripts/update_rtb.sh
