name: Update Candidatura

on:
  workflow_run:
      workflows: ["notify_adding_candidatura"]
      types: 
        - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: list element
      run: dir
      
    - name: Generate Candidatura Markdown Links 
      run: |
        chmod a+x ./bash_scripts/update_candidatura.sh
        ./bash_scripts/update_candidatura.sh

    - name: Checkout code
      uses: actions/checkout@v4

    - name: list element
      run: dir
