name: Update Candidatura

on:
  push:
    paths:
      - '1 - Candidatura/**'
    branches:
      - side-docs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Generate Candidatura Markdown Links 
      run: |
        chmod a+x ./bash_scripts/update_candidatura.sh
        ./bash_scripts/update_candidatura.sh
