name: Update Candidatura

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up VM
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate Markdown Links
      run: |
        folder_path="./docs/Candidatura/"
        markdown_file="prova.md"

        cd "$folder_path" || exit

        for file in *; do
          if [ -f "$file" ]; then
            echo "[${file}](${folder_path}${file})" >> "../$markdown_file"
          fi
        done

        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add "../$markdown_file"
        git commit -m "Update file links"
        git push
