name: Update Candidatura

on:
  push:
    paths:
      - '1 - Candidatura/**'
    branches:
      - side-docs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: list element
      run: dir

    - name: cloining
      run: | 
        git clone 'https://github.com/Carraro-Riccardo/Carraro-Riccardo.github.io'
        cd ./Carraro-Riccardo.github.io
        git checkout 'side-docs'
        git remote set-url origin https://Carraro-Riccardo:${{secrets.TOKEN_GH}}@github.com/Carraro-Riccardo/Carraro-Riccardo.github.io
      
    - name: Generate Candidatura Markdown Links 
      run: |
        chmod a+x ./bash_scripts/update_candidatura.sh
        ./bash_scripts/update_candidatura.sh
