name: Update Candidatura

on:
  push:
    paths:
      - '1 - Candidatura/**'
    branches:
      - side-docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: side-docs

    - name: Generate Candidatura Markdown Links 
      run: |
        chmod a+x ./bash_scripts/update_candidatura.sh
        ./bash_scripts/update_candidatura.sh
