name: LaTeX Compilation

on:
  #triggered when PR is (re)opened or synchronized (new commit to head)
  pull_request:
    types: [opened, reopened]
    paths:
      - '**.tex'

jobs:
  compile-latex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Retrieve pull request information
      env: 
        COMMIT_ID: "${{github.event.pull_request.head.sha}}"
        PR_NUMBER: "${{github.event.pull_request.number}}" 
        PR_TITLE: "${{ github.event.pull_request.title }}"
        AUTHOR: "${{ github.actor }}"
      run: |
        COMMIT_ID=$(echo ${{ github.sha}} | slice -c1-7)
        DATA=$(date)
        echo "$COMMIT_ID;$PR_NUMBER;$PR_TITLE;$AUTHOR;$DATA" > log.txt
        cat log.txt
