name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Restore TeX Live cache
      uses: actions/cache@v2
      with:
        path: /usr/local/texlive # Path to the TeX Live installation directory
        key: texlive-${{ runner.os }}-${{ hashFiles('**/*.tex') }}

    - name: Compile LaTeX Files
      run: |
        chmod a+x ./bash_scripts/latex_autocompile.sh
        ./bash_scripts/latex_autocompile.sh

    - name: Save TeX Live cache
      uses: actions/cache@v2
      with:
        path: /usr/local/texlive
        key: texlive-${{ runner.os }}-${{ hashFiles('**/*.tex') }}
