name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: action
      uses: xu-cheng/latex-action@v3
      with:
        work_in_root_file_dir: ./TexFiles
        args: -pdf
        root_file: |
          *.tex

    - name: Move pdf files
      run: mv *.pdf ./PDF_folder/

    
