name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Restore TeX Live Cache
      uses: actions/cache@v2
      with:
        path: /usr/local/texlive # Path to TeX Live installation
        key: texlive-${{ runner.os }}-${{ hashFiles('**/*.tex') }}
      if: runner.os == 'Linux' # Adjust for other operating systems

    - name: Setup TeX Live
      id: setup-texlive
      uses: josephwright/setup-texlive@v2
      with:
        profile: basic
        package-list: pdflatex

    - name: Install latexmk
      run: tlmgr install latexmk
      if: steps.setup-texlive.outcome == 'success'

    - name: Compile LaTeX Files
      run: |
        chmod a+x ./bash_scripts/latex_autocompile.sh
        ./bash_scripts/latex_autocompile.sh

    - name: Save TeX Live Cache
      uses: actions/cache@v2
      with:
        path: /usr/local/texlive # Path to TeX Live installation
        key: texlive-${{ runner.os }}-${{ hashFiles('**/*.tex') }}
      if: steps.setup-texlive.outcome == 'success'
