name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup TeX Live
      uses: xu-cheng/texlive-action@v2
      with:
        tex-packages: "pdflatex"

    - name: Install latexmk
      run: sudo tlmgr install latexmk

    - name: Compile LaTeX Files
      run: |
        chmod a+x ./bash_scripts/latex_autocompile.sh
        ./bash_scripts/latex_autocompile.sh
