name: Slimmer LaTeX compiler

on:
  #triggered when PR is (re)opened or synchronized (new commit to head)
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**.tex'

jobs:
  compile-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'space-delimited'
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "${changed_file} changed."
            echo "${{ steps.files.outputs.all }};"
          done
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: ${{ github.workspace }}/TexFiles
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: ${{ github.workspace }}/TexFiles/main.pdf
