name: Slimmer LaTeX compiler

on:
  #triggered when PR is (re)opened or synchronized (new commit to head)
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**.tex'

jobs:
  compile-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: List changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'space-delimited'
      - name: Extract path
        id: path
        run: |
          FILES="${{ steps.files.outputs.added_modified }}"
          echo "FILE_PATH=$(dirname "$FILES")" >> $GITHUB_OUTPUT
      - name: Extract name w/o extension
        id: name
        run: |
          FILES="${{ steps.files.outputs.added_modified }}"
          echo "FILE_NAME=$(basename "${FILES}" .tex)" >> $GITHUB_OUTPUT
      - name: Output
        run: |
          echo "Path: ${{ steps.files.outputs.added_modified }}"
          echo "Path: ${{ steps.path.outputs.FILE_PATH }}"
          echo "File: ${{ steps.name.outputs.FILE_NAME }}"
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            ${{ steps.name.outputs.FILE_NAME }}.tex
          working_directory: ${{ github.workspace }}/${{ steps.path.outputs.FILE_PATH }}
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: ${{ github.workspace }}/${{ steps.path.outputs.FILE_PATH }}/${{ steps.name.outputs.FILE_NAME }}.pdf
