name: Slimmer LaTeX compiler

on:
  #triggered when PR is (re)opened or synchronized (new commit to head)
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**.tex'

jobs:
  compile-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: List changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'space-delimited'
      - name: Compile LaTeX document(s)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            ${{ steps.files.outputs.added_modified }}
          #working_directory: ${{ github.workspace }}/TexFiles
      - name: Upload PDF file(s)
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: ${{ github.workspace }}/TexFiles/main.pdf
