name: Update Candidatura

on:
  push:
    branches:
      - side-docs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: create File
      run: |
        echo "ciao" > prova.txt
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add "./prova.txt"
        git commit -m "Update file links"
        git push 
