name: Update Candidatura

on:
  push:
    branches:
      - site-docs
    paths:
      - '1 - Candidatura/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: list element
      run: dir
      
    - name: Generate Candidatura Markdown Links 
      run: |
        git clone -b try-change-path --single-branch 'https://github.com/Carraro-Riccardo/Carraro-Riccardo.github.io'
        cd ./Carraro-Riccardo.github.io/bash_scripts
        mv 'update_canidatura.sh' '../../'
        cd ../../ 
        dir
        chmod a+x ./bash_scripts/update_candidatura.sh
        ./bash_scripts/update_candidatura.sh
        

    - name: Checkout code
      uses: actions/checkout@v4

    - name: list element
      run: dir
